# SPDX-FileCopyrightText: 2022 nerdyscout <https://github.com/nerdyscout/>
#
# SPDX-License-Identifier: CC0-1.0

name: Release

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      version:
        description: "draft release"
        required: true
        default: "pre-release"